export const bvm_demo = [
    {
      "cwpi_score": 0,
      "color": "red",
      "department_id": 1,
      "department_name": "Building Constructive Department(BCD)",
      "department_short_name": "BADA",
      "month": 2,
      "percentile": 68,
      "performance_percent": 0,
      "project_count": 0,
      "rank": 4,
      "year": 2024
    },
    {
      "cwpi_score": 0,
      "color": "Green",
      "department_id": 2,
      "department_name": "Building Constructive Department(BCD)",
      "department_short_name": "BCD",
      "month": 2,
      "percentile": 68,
      "performance_percent": 0,
      "project_count": 0,
      "rank": 3,
      "year": 2024
    },
    {
      "cwpi_score": 0,
      "color": "Green",
      "department_id": 3,
      "department_name": "Building Constructive Department(BCD)",
      "department_short_name": "BCD",
      "month": 2,
      "percentile": 68,
      "performance_percent": 0,
      "project_count": 0,
      "rank": 1,
      "year": 2024
    },
    {
      "cwpi_score": 0,
      "color": "Green",
      "department_id": 4,
      "department_name": "Building Constructive Department(BCD)",
      "department_short_name": "BCD",
      "month": 2,
      "percentile": 68,
      "performance_percent": 0,
      "project_count": 0,
      "rank": 2,
      "year": 2024
    },
    {
      "cwpi_score": 0,
      "color": "Green",
      "department_id": 5,
      "department_name": "Building Constructive Department(BCD)",
      "department_short_name": "BCD",
      "month": 2,
      "percentile": 68,
      "performance_percent": 0,
      "project_count": 0,
      "rank": 5,
      "year": 2024
    },
    {
      "cwpi_score": 0,
      "color": "Green",
      "department_id": 6,
      "department_name": "Building Constructive Department(BCD)",
      "department_short_name": "BCD",
      "month": 2,
      "percentile": 68,
      "performance_percent": 0,
      "project_count": 0,
      "rank": 8,
      "year": 2024
    },
    {
      "cwpi_score": 0,
      "color": "Green",
      "department_id": 7,
      "department_name": "Building Constructive Department(BCD)",
      "department_short_name": "BCD",
      "month": 2,
      "percentile": 68,
      "performance_percent": 0,
      "project_count": 0,
      "rank": 7,
      "year": 2024
    },
    {
      "cwpi_score": 0,
      "color": "Green",
      "department_id": 8,
      "department_name": "Building Constructive Department(BCD)",
      "department_short_name": "BCD",
      "month": 2,
      "percentile": 68,
      "performance_percent": 0,
      "project_count": 0,
      "rank": 6,
      "year": 2024
    },
    {
      "cwpi_score": 0,
      "color": "Green",
      "department_id": 9,
      "department_name": "Building Constructive Department(BCD)",
      "department_short_name": "BCD",
      "month": 2,
      "percentile": 68,
      "performance_percent": 0,
      "project_count": 0,
      "rank": 9,
      "year": 2024
    },
    {
      "cwpi_score": 0,
      "color": "Green",
      "department_id": 10,
      "department_name": "Building Constructive Department(BCD)",
      "department_short_name": "BCD",
      "month": 2,
      "percentile": 68,
      "performance_percent": 0,
      "project_count": 0,
      "rank": 10,
      "year": 2024
    },
    {
      "cwpi_score": 0,
      "color": "Green",
      "department_id": 11,
      "department_name": "Building Constructive Department(BCD)",
      "department_short_name": "BCD",
      "month": 2,
      "percentile": 68,
      "performance_percent": 0,
      "project_count": 0,
      "rank": 11,
      "year": 2024
    },
    {
      "cwpi_score": 0,
      "color": "Green",
      "department_id": 12,
      "department_name": "Building Constructive Department(BCD)",
      "department_short_name": "BCD",
      "month": 2,
      "percentile": 68,
      "performance_percent": 0,
      "project_count": 0,
      "rank": 12,
      "year": 2024
    },
    {
      "cwpi_score": 0,
      "color": "Green",
      "department_id": 13,
      "department_name": "Building Constructive Department(BCD)",
      "department_short_name": "BCD",
      "month": 2,
      "percentile": 68,
      "performance_percent": 0,
      "project_count": 0,
      "rank": 15,
      "year": 2024
    },
    {
      "cwpi_score": 0,
      "color": "Green",
      "department_id": 14,
      "department_name": "Building Constructive Department(BCD)",
      "department_short_name": "BCD",
      "month": 2,
      "percentile": 68,
      "performance_percent": 0,
      "project_count": 0,
      "rank": 13,
      "year": 2024
    },
    {
      "cwpi_score": 0,
      "color": "Green",
      "department_id": 15,
      "department_name": "Building Constructive Department(BCD)",
      "department_short_name": "BCD",
      "month": 2,
      "percentile": 68,
      "performance_percent": 0,
      "project_count": 0,
      "rank": 14,
      "year": 2024
    },
    {
      "cwpi_score": 0,
      "color": "Green",
      "department_id": 16,
      "department_name": "Building Constructive Department(BCD)",
      "department_short_name": "BCD",
      "month": 2,
      "percentile": 68,
      "performance_percent": 0,
      "project_count": 0,
      "rank": 17,
      "year": 2024
    },
    {
      "cwpi_score": 0,
      "color": "Green",
      "department_id": 17,
      "department_name": "Building Constructive Department(BCD)",
      "department_short_name": "BCD",
      "month": 2,
      "percentile": 68,
      "performance_percent": 0,
      "project_count": 0,
      "rank": 16,
      "year": 2024
    },
    {
      "cwpi_score": 0,
      "color": "Green",
      "department_id": 15,
      "department_name": "Building Constructive Department(BCD)",
      "department_short_name": "BCD",
      "month": 2,
      "percentile": 68,
      "performance_percent": 0,
      "project_count": 0,
      "rank": 18,
      "year": 2024
    },
    {
      "cwpi_score": 0,
      "color": "Green",
      "department_id": 16,
      "department_name": "Building Constructive Department(BCD)",
      "department_short_name": "Bada",
      "month": 2,
      "percentile": 68,
      "performance_percent": 0,
      "project_count": 0,
      "rank": 19,
      "year": 2024
    }


  ]
  